import "./globals.css";
import { Inter } from "next/font/google";
import { FileContextProvider } from "./context/FileContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PSPDF KIT TEST",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-900`}>
        <FileContextProvider>{children}</FileContextProvider>
      </body>
    </html>
  );
}
